### ISSUE TITLE
resr

### ISSUE THREAD

**Issue by jeffersonDSN** [jeffersonDSN/agtmovel#8]
```yaml
start_date: 2024/06/29
due_date: 2024/07/04
progress: 0
parent: 7
```
