### ISSUE TITLE
89

### ISSUE THREAD

**Issue by jeffersonDSN** [jeffersonDSN/agtmovel#9]
```yaml
start_date: 2024/06/28
due_date: 2024/07/11
progress: 0
parent: 8
```
